travis:
  secure:
    BINSTAR_TOKEN: 0PMkk0vhZq/wb6EBpwJ3UNf1cPVBoXsirqItwep4jwZPlj7CMzqQXEWv4HlJV0wy+kY4qy0X/B2/C0xVvWGhvqZwj7ZKUEzv30ImMW5r7MqGDRexjnbUiKhAZH/eJDWxy3FqbJCsABgXNju0VI1DkRKIxcE1epriNKHjZ+TnbEFzu7934h2LB9B0ST6t81BdtdCtnf8FYc3LSPwzuNa9TFi++Vc0t5aAOBnDPGxvuw7pwPdbMuu/BQVGS+Ww6rFMAuwyn/OpZBm/9FRoJzB60p6Y4Yh/5h00GQ0Wy71Sh2Vl6qTtF/ZYyUgxAehyHDkoBeRl5+JPdqXgHTyPqYXHoLI3+bJbyd0QT6U4nt9oTk45rYG07PquksbjZXGII7iJvn3zi1q639FeyJ5GV4RGu2GBmZb+KssWM9rSazyUDcSJoajkmYAROjVji+/KoArgQT/zP67vEUHYxuD2iqxmLUd7Paoniw2zbTUze5NLe8qmqyCOI9WYCKQHHQ/CTpGAo6zBUofE3UJy+/sNh/tCL8R1RcqoDjPZxdCPALaMbpqmJy9yF9/1Fh+AHLlJytPfovTecpqBPTCyZQUZUGYU+Gng3VYb3cHb194HWCype2Fj865X6Le2sjAlI/p7nN2+GvWFue0dkQhSk8V10BCWoWJZi8Q5He87cXl0n3t9IT0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
